import { describe, expect, it } from 'vitest';
import {
  FILE_DROP_MAX_CANDIDATES,
  FILE_DROP_MAX_CANDIDATE_LENGTH,
  extractFileDropCandidates,
  type FileDropData,
} from './file-drop';

function transfer(input: Partial<FileDropData> = {}): FileDropData {
  return {
    files: input.files ?? [],
    types: input.types ?? [],
    getData: input.getData ?? (() => ''),
  };
}

describe('extractFileDropCandidates', () => {
  it.each([
    {
      name: 'normalizes URI-list comments, blank lines, and CRLF without decoding',
      value: '# generated by browser\r\nfile:///workspace/a%20b.ts\r\n\r\nfile:///workspace/c.ts\r\n',
      expected: ['file:///workspace/a%20b.ts', 'file:///workspace/c.ts'],
    },
    {
      name: 'hands percent encoding to the host unchanged',
      value: 'file:///workspace/%E2%9C%93.ts',
      expected: ['file:///workspace/%E2%9C%93.ts'],
    },
  ])('$name', ({ value, expected }) => {
    const data = transfer({
      types: ['text/uri-list'],
      getData: (type) => (type === 'text/uri-list' ? value : ''),
    });
    expect(extractFileDropCandidates(data, true)).toEqual({ ok: true, candidates: expected });
  });

  it('uses an explicit File.path but never falls back to File.name', () => {
    const data = transfer({ files: [{ name: 'ignored.ts' }, { name: 'safe.ts', path: '/workspace/safe.ts' }] });
    expect(extractFileDropCandidates(data, true)).toEqual({
      ok: true,
      candidates: ['/workspace/safe.ts'],
    });
  });

  it('accepts explicit plain-text transfer data as one opaque host candidate', () => {
    const data = transfer({
      types: ['text/plain', 'text/html'],
      getData: (type) => (type === 'text/plain' ? 'src/a.ts' : '<b>secret</b>'),
    });
    expect(extractFileDropCandidates(data, true)).toEqual({ ok: true, candidates: ['src/a.ts'] });
  });

  it.each([
    ['disabled composer', transfer(), false, { ok: false, code: 'disabled', message: 'File drop is unavailable.' }],
    ['no supported data', transfer({ types: ['text/html'], getData: () => '<b>x</b>' }), true, { ok: false, code: 'noData', message: 'No supported file data was dropped.' }],
    ['empty URI list', transfer({ types: ['text/uri-list'], getData: () => '# comment\n' }), true, { ok: false, code: 'noData', message: 'No supported file data was dropped.' }],
  ])('rejects %s', (_name, data, enabled, expected) => {
    expect(extractFileDropCandidates(data as FileDropData, enabled as boolean)).toEqual(expected);
  });

  it('rejects excessive candidates instead of truncating silently', () => {
    const value = Array.from({ length: FILE_DROP_MAX_CANDIDATES + 1 }, (_, i) => `file:///workspace/${i}.ts`).join('\n');
    expect(extractFileDropCandidates(transfer({ types: ['text/uri-list'], getData: () => value }), true)).toEqual({
      ok: false,
      code: 'tooManyCandidates',
      message: `Drop at most ${FILE_DROP_MAX_CANDIDATES} file candidates.`,
    });
  });

  it('rejects overlong and NUL-containing candidates', () => {
    const tooLong = 'a'.repeat(FILE_DROP_MAX_CANDIDATE_LENGTH + 1);
    for (const value of [tooLong, 'file:///workspace/a\0.ts']) {
      expect(extractFileDropCandidates(transfer({ types: ['text/plain'], getData: () => value }), true)).toEqual({
        ok: false,
        code: 'invalidCandidate',
        message: 'Dropped file data is malformed or too long.',
      });
    }
  });

  it('deduplicates identical candidates while preserving source order', () => {
    const data = transfer({
      files: [{ path: '/workspace/a.ts' }],
      types: ['text/uri-list'],
      getData: () => '/workspace/a.ts\nfile:///workspace/b.ts',
    });
    expect(extractFileDropCandidates(data, true)).toEqual({
      ok: true,
      candidates: ['/workspace/a.ts', 'file:///workspace/b.ts'],
    });
  });
});
